version: '2.1'
services:
  api-gateway:
    container_name: api-gateway
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'

      # Destinos
      DESTINATIONS_URL: '54.237.247.170'
      DESTINATIONS_PORT: '3001'
      DESTINATIONS_ENTRY: 'destinations'
      
      # Eventos
      EVENTS_URL: '18.233.158.9'
      EVENTS_PORT: '3003'
      EVENTS_ENTRY: 'events'
      RESERVATIONS_URL: '18.233.158.9'
      RESERVATIONS_PORT: '3003'
      RESERVATIONS_ENTRY: 'reservations'
      
      # Login
      USERS_URL: '54.224.94.195'
      USERS_PORT: '3002'
      USERS_ENTRY: 'users'
      PASSENGERS_URL: '54.224.94.195'
      PASSENGERS_PORT: '3002'
      PASSENGERS_ENTRY: 'passengers'
      CREWS_URL: '54.224.94.195'
      CREWS_PORT: '3002'
      CREWS_ENTRY: 'crews'

      # Notifications
      NOTIFICATIONS_URL: '34.227.117.230'
      NOTIFICATIONS_PORT: '3004'
      NOTIFICATIONS_ENTRY: 'notifications'
      
      # Promociones
      PROMOCIONES_URL: '52.201.234.125'
      PROMOCIONES_PORT: '3000'
      PROMOCIONES_ENTRY: 'promociones'
      TIENDAS_URL: '52.201.234.125'
      TIENDAS_PORT: '3000'
      TIENDAS_ENTRY: 'tiendas'

      # Servidor LDAP
      LDAP_URL:  '3.93.247.219'
      LDAP_PORT: '389'
      LDAP_ENTRY:  'auth'

    ports:
      - '5000:5000'
