version: '2.1'
services:
  api-gateway:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      ## TO-DO: Modificar variables de entorno
      EVENTS_URL: '52.201.215.111'
      EVENTS_PORT: '3000'
      EVENTS_ENTRY: 'events'
      DESTINATIONS_URL: '3.82.145.168'
      DESTINATIONS_PORT: '3000'
      DESTINATIONS_ENTRY: 'destinations'
      # Login
      USERS_URL: '3.82.217.243'
      USERS_PORT: '3000'
      USERS_ENTRY: 'users'
      PASSENGERS_URL: '3.82.217.243'
      PASSENGERS_PORT: '3000'
      PASSENGERS_ENTRY: 'passengers'
      CREWS_URL: '3.82.217.243'
      CREWS_PORT: '3000'
      CREWS_ENTRY: 'crews'
      # Promociones
      PROMOCIONES_URL: '34.239.104.208'
      PROMOCIONES_PORT: '3000'
      PROMOCIONES_ENTRY: 'promociones'
      TIENDAS_URL: '34.239.104.208'
      TIENDAS_PORT: '3000'
      TIENDAS_ENTRY: 'tiendas'
    ports:
      - '5000:5000'