version: '2.1'
services:
  api-gateway:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      ## TO-DO: Modificar variables de entorno
      EVENTS_URL: '192.168.99.101'
      EVENTS_PORT: '3000'
      EVENTS_ENTRY: 'events'
      DESTINATIONS_URL: '192.168.99.101'
      DESTINATIONS_PORT: '3001'
      DESTINATIONS_ENTRY: 'destinations'
    ports:
      - '5000:5000'